#! /bin/bash

# License
# All scripts are licensed under the 
# GNU Public License v3.0 or later.
# See license details here: https://www.gnu.org/licenses/gpl-3.0.html

#
# renames media files handled by exiftool to <timestamp>.<ext>
#
# Limitations:
#   - works with files that exiftool can process
#   - extensions that are 3 or 4 chars long
#   - issues when daylight savings is used....
#
#LOG=/tmp/test.log
while IFS= read -r line; do
#   echo "line: \"$line\""  >> $LOG
   FILENAME="$line"
#   echo "==> process: \"$FILENAME\"" >> $LOG
   if [[ -z $FILENAME ]]; then
    continue
   fi
   EXT=$(echo "$FILENAME" |egrep -o "\.[a-zA-Z0-9]*$")
   NAME=$(exiftool -P -d '%Y-%m-%d_%H:%M:%S'  -CreateDate "$FILENAME" |awk '{print $4" "$5}'|sed 's|[ \t]*$||')
   SUBSEC=$(exiftool -P -SubSecTimeDigitized "$FILENAME"|awk '{print $6}')
#   echo "-CreateDate generated: \"$NAME\"" >> $LOG
   if [[ -z "$NAME" ]]; then
     NAME=$(exiftool -P -d '%Y-%m-%d_%H:%M:%S' -FileModifyDate "$FILENAME" |awk '{print $5" "$6}'|sed 's|[ \t]*$||')
#     echo "-FileModifyDate generated: \"$NAME\"" >> $LOG
   fi
   if [[ ! -z "$NAME" ]]; then
#      echo "\"$FILENAME\" ==> \"$NAME$EXT\"" >> $LOG
      #mv "$FILENAME" "${NAME},${SUBSEC}${EXT}"
      cp "$FILENAME" "${NAME},${SUBSEC}${EXT}"
   fi	   
done <<< "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS"

